language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - com.google.firebase:firebase-auth:11.0.2
    - com.google.android.gms:play-services-auth:11.0.2
    - com.google.firebase:firebase-core:11.0.2
    - com.google.firebase:firebase-database:11.0.2
    - com.android.support:appcompat-v7:23.4.0
    - com.android.support.constraint:constraint-layout:1.0.2
    - org.jsoup:jsoup:1.10.3
    - com.squareup.picasso:picasso:2.5.2
    - com.android.support:design:23.4.0
    - junit:junit:4.12

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
